### PR TITLE
TST: adds async tests and uses closures

### PR DESCRIPTION
**Pull request by ebolyen**
This depends on a framework update to allow closures to be used.

### CODE REVIEW

**Comment by ebolyen** [comment]
depends on https://github.com/qiime2/qiime2/pull/584

**Comment by ebolyen** [comment]
Looks like there are fundamental issues in the framework when combining `.add_plugin()` and `.asynchronous`. 
@Oddant1 this may be worth keeping in mind for your work with Parsl. The plugin manager's state is not generally shipped anywhere, so if the plugin manager is initialized in a way that doesn't use entry-points (or if the entry-points are different on the remote system), provenance capture seems to fail because it attempts to look up the used plugin via the string ID (which hasn't been added).

Interestingly, for this PR, linux behaves differently than OS X, in that linux will share the module globals between processes via some kind of shared memory, whereas OS X makes no attempt.

**Comment by ebolyen** [comment]
marking this 'cant-fix' for now...

**Comment by ebolyen** [comment]
Here's the reason: https://stackoverflow.com/a/61863247/579416

**Comment by lizgehret** [comment]
Hey @ebolyen @Oddant1 is this still current?

**Comment by ebolyen** [comment]
Closing for now, as there's really no workable solution.

**Pull request closed without merging**
